### ISSUE TITLE
Fixes & Features

### ISSUE THREAD

**Issue by chadleylyell** [ifedapoolarewaju/igdm#164]
Could you guys please fix some things, and implement some stuff...
# Fix:
• When someone likes a DM you sent, it sends a message from that person saying "<unsupported message format>"... Just make it so it adds a heart under your message sent, or something.

• You can only see your latest 20 people DM'd... It'd me nice if the list grew as you got to the bottom.

• You can only see the latest 20 DM's sent to someone... as mentioned above, it'd be nice ^

• Group DM's don't show the name of the group, it just has a list of all the people in the group... please fix

• When someone is tagged in DM's, that persons name doesn't show up blue... Maybe make it when you click the name tagged, their picture pops up, and a button shows saying "view profile" and it open instagram.com/user_name in browser...

• When someone shares a profile with you via DM's a message comes from that person saying "<unsupported message format>"... Make it to where it shows that person's name as a tag or whatever.
 
# Implement:
∆• Like a DM someone sent

∆• "Unsend" DM's (delete the DM)

∆• Add members to group DM

• Rename group DM

• Change "seen" to an eye or something and move it to under the message instead of all the way over to the left

∆ = I really would like to see this feature, and should be implemented anyways....
These are just some features I really think should be implemented, and some fixes I would like to see.

**Comment by Tahsinahrar** [comment]
<3 <3 Exactly

**Comment by ajaygrover** [comment]
I recently broke my phone and started using this application for Instagram DM's (I could find no alternatives).

chadleylyell did a good job listing out the enhancements and or features that I would also love to have. 

I went through the code base to see how it works. 

Instagram apparently internally uses two different Endpoints for WebRequests and Android/IOS App Requests (not completly sure). The former is used to get Direct Message Information. 

Instagram's application uses Web Sockets to do real-time communication, while the instagram-private-api-v1 uses pooling. Which is just getting the same data every x seconds and updating it. Doing this is not the ideal solution as we are essentially getting the same data redundantly while we should only get the data which needs to be updated in the view.

Check this old issue regarding the same  https://github.com/huttarichard/instagram-private-api/issues/13 


I thought about implementing
=> Loading of more than 20 chats / chat messages.

Due to above said limitations I cannot find any way to get chats using a cursor or getting chat list efficiently using range. which means i cannot get just the older chats. If i want to get more "chat" it will come with a baggage of ALL the "chats", even the ones that are already displaying.

I suppose this is a dirty solution because it would increase memory, internet and other resource usage as you start loading more and more message.

BUT, on the other hand it would just get the job done. 

I might be completely wrong and their might be a way to just get older messages / chats.

I will happy to make necessary changes after more view points from other people. As this could do more bad to the application than good.

**Comment by chadleylyell** [comment]
@ifedapoolarewaju ^^^

**Comment by ifedapoolarewaju** [comment]
@ajaygrover thank you for giving this a spin. Right now we fetch messages with the [Thread](https://github.com/huttarichard/instagram-private-api/blob/master/client/v1/thread.js#L214) class. I think if we used [ThreadItemsFeed](https://github.com/huttarichard/instagram-private-api/blob/master/client/v1/feeds/thread-items.js) to get the messages instead, then we would have the cursor to load messages in ranges. Does this make sense to you?
