### ISSUE TITLE
Latest update broke the linux appimage

### ISSUE THREAD

**Issue by neeeeeem** [ifedapoolarewaju/igdm#375]
I tried to get the newest version of igdm, but it gives this error message: fyi I use Arch Linux, so I can't exactly use deb or rpm.
`module.js:545`
`    throw err;`
`    ^`

`Error: Cannot find module '/tmp/.mount_IGdm-2ja4yr9/resources/electron.asar/browser/init.js'`
`    at Function.Module._resolveFilename (module.js:543:15)`
`    at Function.Module._load (module.js:473:25)`
`    at Function.Module.runMain (module.js:683:10)`
`    at startup (bootstrap_node.js:196:16)`
`    at bootstrap_node.js:622:3`

looks like whatever electron builder has issues again?
(edit, fixing format)

**Comment by SimonVanacco** [comment]
Here is a workaroud while waiting the .appimage to be fixed:

Go here: [IGdm Github Releases](https://github.com/ifedapoolarewaju/igdm/releases) and download the .zip from the latest release (2.5.1 to this day). Unzip it, launch it, Boom it works.

BTW, this should be fixed by PR #374, watch that to know when it will be fixed ;)
Good day sir,

Simon
