### ISSUE TITLE
This is FALSE ADVERTISEMENT!

### ISSUE THREAD

**Issue by pgarner09** [ifedapoolarewaju/igdm#446]
It won't let me login. Saying that 'Instagram call checkpoint for this action!' I downloaded IG:DM to view my messages, but if I can't do that then there is no point of even having downloaded it. Please try to fix the problem and do a test before publishing your software. It keeps everyone happy and from causing a lot of trouble and bad comments for the publisher. Whoever that may be.

**Comment by Slater91** [comment]
False advertisement? "Do a test before publishing your software"? You know nothing about how software works, even less about how to develop, and apparently even less about how to use GitHub (like, there are already tens of bugs open on this same issue by clueless people like you who don't know the basics of how to use GitHub). Yet you are here complaining. Your arrogance knows no limits. This is surreal.
Just understand that the world doesn't turn around you. Learn something and contribute to the project, otherwise just shut up and ask "could you **_please_** fix the software as I like to use it?".

**Comment by gusbemacbe** [comment]
What a troll!
