### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Git-HubMat** [ifedapoolarewaju/igdm#47]
How does sending images work? i cant seem to do it

**Comment by ifedapoolarewaju** [comment]
Hi it currently only accepts just `jpg` and `jpeg`, perhaps that's the problem? Are you sending other formats?

**Comment by Git-HubMat** [comment]
Thanks for responding no im using those formats. The pictures just wern't loading went i sent them i had to reload the chat.

**Comment by Git-HubMat** [comment]
*when

**Comment by ifedapoolarewaju** [comment]
so you don't see the image after you reload?

**Comment by Git-HubMat** [comment]
No I didn't see the image before I reloaded.

**Comment by ifedapoolarewaju** [comment]
but you saw it after?

**Comment by Git-HubMat** [comment]
Yes,  it may be a bug that it does not load the moment you send it.

**Comment by Git-HubMat** [comment]
It is not a big problem to me. Just mentioning it. Sorry for wasting your time and I absolutely love this app.

**Comment by ifedapoolarewaju** [comment]
@Git-HubMat of course, thank you for reporting! 🙂  I think the issue is that there isn't enough interactive UI feedback while the image is being sent (I'll work on that). But from what I have tested the image does get sent and it gets displayed in the UI afterwards.

But maybe for some reason (e.g the file you sent is large), it took a while to update, so you got the impression it wasn't working.

**Comment by ninjawesomee** [comment]
i try sending images too same format and reloaded the chat but it dont load and the person dont get it either
