### ISSUE TITLE
Messages not being sent

### ISSUE THREAD

**Issue by abuggm** [ifedapoolarewaju/igdm#643]
Hello, when I use your desktop app (on windows 7, running it as an administrator), old messages show, but when I try to type a new one, it becomes stuck on "sending" and never actually sends it.. Any ideas whats wrong?

**Comment by asianowned** [comment]
I think IGDM had been hacked. There are thousands of complaints of security issuers and none of their software working and they have not answered even one. my Instagram desk top messenger stopped working last month and since then they been try to ask me too many personal security questions and asking to make too many passwords. I think I have to delete them. Even my virus program is telling not to trust them anymore. I think there web service has been hijacked or abandoned.
