### ISSUE TITLE
Can't sign in, Can't send text, etc.

### ISSUE THREAD

**Issue by freak9102** [ifedapoolarewaju/igdm#827]
I have been trying to text people but it will take forever to send. It also didn’t want to let me sign in. I had to keep spamming the login to Instagram button to finally get in. Can you please explain to me what’s going on? And how I can update the app? You guys are literally no help.

**Comment by freak9102** [comment]
No, it didn't help. How about you be more useful and tell me how to resolve this.

**Comment by cavi21** [comment]
@freak9102 as you may notice this application is OS, that's mean that everyone can help, also you :)

What I'm trying to say is that the maintainers are people like you and me that have limited time to look into all this issues, and they are doing it for free and in their spare time I imagine.

This issue seems to be with something that change from the Instagram side, probably with the responso payload. If you are in a hurry you can debug the issue by yourself and trying to open a PR proposing a change.

Hope you took this in good way because there is no other intention that trying to collaborate and help.
Have a great day!

**Comment by cavi21** [comment]
This is an issue in IG, you can check that their service is experiencing [outages](https://outage.report/instagram)
